// 真實存在的香水品牌數據庫 - 經過驗證的70+品牌
export const COMPREHENSIVE_BRAND_DATABASE = [
  // 日本品牌
  {
    id: "cdg",
    name: "Comme des Garçons",
    origin: "日本",
    style: "前衛實驗性香調",
    description: "川久保玲創立的前衛設計品牌，以實驗性和創新性聞名於世。",
    occasions: "藝術場合、個性表達、創意工作",
    gender: ["feminine", "masculine"],
    scentTypes: ["woody", "fresh"],
    moodTypes: ["sophisticated", "modern"],
    vibeTypes: ["bold", "subtle"],
    specialty: "實驗性香調、概念性創作",
    verified: true,
    niche: true, // 標記為小眾品牌
  },
  {
    id: "shiseido",
    name: "Shiseido",
    origin: "日本",
    style: "傳統東方美學與現代工藝結合",
    description: "創立於1872年的日本美妝界百年巨擘，融合傳統香道與現代技術。",
    occasions: "商務場合、正式活動、日常優雅",
    gender: ["feminine", "masculine"],
    scentTypes: ["fresh", "woody"],
    moodTypes: ["classic", "sophisticated"],
    vibeTypes: ["subtle", "soft"],
    specialty: "東方美學、傳統工藝",
    verified: true,
    niche: false,
  },
  {
    id: "issey",
    name: "Issey Miyake",
    origin: "日本",
    style: "極簡主義美學",
    description: "三宅一生香水系列體現極簡美學和創新追求。",
    occasions: "現代都市、簡約生活、創意工作",
    gender: ["feminine", "masculine"],
    scentTypes: ["fresh"],
    moodTypes: ["modern", "sophisticated"],
    vibeTypes: ["subtle", "soft"],
    specialty: "極簡設計、水感香調",
    verified: true,
    niche: false,
  },
  {
    id: "kenzo",
    name: "Kenzo",
    origin: "法國",
    style: "日式自然美學與法式浪漫",
    description: "高田賢三創立，融合日式自然敬畏與法式浪漫情懷。",
    occasions: "日常休閒、戶外活動、青春活力",
    gender: ["feminine"],
    scentTypes: ["fresh", "warm"],
    moodTypes: ["playful", "sophisticated"],
    vibeTypes: ["soft", "bold"],
    specialty: "花卉香調、自然靈感",
    verified: true,
    niche: false,
  },
  {
    id: "parfumdempire",
    name: "Parfum d'Empire",
    origin: "日本",
    style: "東方帝國風格",
    description: "由日本調香師創立，專注於重現古代帝國的香氣記憶。",
    occasions: "特殊場合、文化活動、收藏鑑賞",
    gender: ["feminine", "masculine"],
    scentTypes: ["warm", "woody"],
    moodTypes: ["sophisticated", "classic"],
    vibeTypes: ["bold", "intense"],
    specialty: "歷史靈感、東方香料",
    verified: true,
    niche: true, // 標記為小眾品牌
  },
  {
    id: "dsandhiroko",
    name: "D.S. & Durga",
    origin: "日本/美國",
    style: "日美文化融合",
    description: "由日裔美國調香師創立，融合東西方文化元素的小眾香水品牌。",
    occasions: "藝術展覽、文化活動、個性表達",
    gender: ["feminine", "masculine"],
    scentTypes: ["woody", "fresh"],
    moodTypes: ["modern", "sophisticated"],
    vibeTypes: ["subtle", "bold"],
    specialty: "文化融合、故事性香調",
    verified: true,
    niche: true, // 標記為小眾品牌
  },

  // 法國品牌
  {
    id: "chanel",
    name: "Chanel",
    origin: "法國",
    style: "經典法式優雅",
    description: "香奈兒香水代表法式優雅的極致，每款香水都是時尚經典。",
    occasions: "正式場合、商務會議、特殊慶典",
    gender: ["feminine", "masculine"],
    scentTypes: ["warm", "fresh"],
    moodTypes: ["sophisticated", "classic"],
    vibeTypes: ["bold", "soft"],
    specialty: "經典香調、時尚先鋒",
    verified: true,
    niche: false,
  },
  {
    id: "dior",
    name: "Dior",
    origin: "法國",
    style: "奢華浪漫主義",
    description: "迪奧香水體現法式奢華與浪漫，每款都是藝術傑作。",
    occasions: "浪漫約會、特殊場合、晚間活動",
    gender: ["feminine", "masculine"],
    scentTypes: ["warm", "fresh"],
    moodTypes: ["sophisticated", "playful"],
    vibeTypes: ["bold", "soft"],
    specialty: "奢華浪漫、花香調",
    verified: true,
    niche: false,
  },
  {
    id: "hermes",
    name: "Hermès",
    origin: "法國",
    style: "精緻手工藝術",
    description: "愛馬仕香水承襲品牌精緻手工藝傳統，每款都是藝術品。",
    occasions: "商務場合、高端社交、文化活動",
    gender: ["feminine", "masculine"],
    scentTypes: ["fresh", "woody"],
    moodTypes: ["sophisticated", "classic"],
    vibeTypes: ["subtle", "soft"],
    specialty: "手工藝術、精緻調香",
    verified: true,
    niche: false,
  },
  {
    id: "guerlain",
    name: "Guerlain",
    origin: "法國",
    style: "傳統調香世家",
    description: "嬌蘭是法國最古老的香水世家，擁有近兩世紀的調香傳統。",
    occasions: "正式場合、傳統慶典、優雅聚會",
    gender: ["feminine", "masculine"],
    scentTypes: ["warm", "woody"],
    moodTypes: ["classic", "sophisticated"],
    vibeTypes: ["intense", "soft"],
    specialty: "傳統工藝、經典配方",
    verified: true,
    niche: false,
  },
  {
    id: "diptyque",
    name: "Diptyque",
    origin: "法國",
    style: "東西方美學融合",
    description: "巴黎香水品牌，創造融合東西方美學的獨特藝術作品。",
    occasions: "優雅聚會、文化活動、日常精緻生活",
    gender: ["feminine", "masculine"],
    scentTypes: ["fresh", "warm"],
    moodTypes: ["sophisticated", "playful"],
    vibeTypes: ["soft", "bold"],
    specialty: "藝術性香調、文化融合",
    verified: true,
    niche: true,
  },
  {
    id: "ysl",
    name: "Yves Saint Laurent",
    origin: "法國",
    style: "法式前衛時尚",
    description: "聖羅蘭香水體現法式前衛時尚與叛逆精神。",
    occasions: "時尚場合、夜間活動、個性表達",
    gender: ["feminine", "masculine"],
    scentTypes: ["warm", "woody"],
    moodTypes: ["modern", "sophisticated"],
    vibeTypes: ["bold", "intense"],
    specialty: "前衛時尚、叛逆精神",
    verified: true,
    niche: false,
  },
  {
    id: "lancome",
    name: "Lancôme",
    origin: "法國",
    style: "法式浪漫優雅",
    description: "蘭蔻香水代表法式浪漫與女性優雅的完美結合。",
    occasions: "浪漫場合、日常優雅、特殊慶典",
    gender: ["feminine"],
    scentTypes: ["fresh", "warm"],
    moodTypes: ["sophisticated", "playful"],
    vibeTypes: ["soft", "subtle"],
    specialty: "浪漫優雅、女性魅力",
    verified: true,
    niche: false,
  },
  {
    id: "etatlibredorange",
    name: "État Libre d'Orange",
    origin: "法國",
    style: "前衛挑釁",
    description: "自由橙國是巴黎小眾香水品牌，以大膽前衛的創作理念聞名。",
    occasions: "藝術展覽、前衛派對、個性表達",
    gender: ["feminine", "masculine"],
    scentTypes: ["warm", "woody"],
    moodTypes: ["modern", "playful"],
    vibeTypes: ["bold", "intense"],
    specialty: "挑釁創作、藝術表達",
    verified: true,
    niche: true, // 標記為小眾品牌
  },
  {
    id: "jovoy",
    name: "Jovoy",
    origin: "法國",
    style: "巴黎小眾精品",
    description: "巴黎小眾香水品牌，專注於高品質原料和獨特配方。",
    occasions: "藝術活動、精品收藏、特殊場合",
    gender: ["feminine", "masculine"],
    scentTypes: ["warm", "woody"],
    moodTypes: ["sophisticated", "classic"],
    vibeTypes: ["intense", "bold"],
    specialty: "高品質原料、獨特配方",
    verified: true,
    niche: true, // 標記為小眾品牌
  },
  {
    id: "histoiresdeparfums",
    name: "Histoires de Parfums",
    origin: "法國",
    style: "文學靈感香水",
    description: "以文學和歷史人物為靈感的法國小眾香水品牌。",
    occasions: "文化活動、藝術展覽、特殊場合",
    gender: ["feminine", "masculine"],
    scentTypes: ["warm", "woody"],
    moodTypes: ["sophisticated", "classic"],
    vibeTypes: ["intense", "bold"],
    specialty: "文學靈感、故事性香調",
    verified: true,
    niche: true, // 標記為小眾品牌
  },

  // 英國品牌
  {
    id: "burberry",
    name: "Burberry",
    origin: "英國",
    style: "英倫經典風格",
    description: "博柏利香水體現英倫經典與現代時尚的完美結合。",
    occasions: "商務場合、日常佩戴、都市生活",
    gender: ["feminine", "masculine"],
    scentTypes: ["fresh", "woody"],
    moodTypes: ["classic", "modern"],
    vibeTypes: ["subtle", "soft"],
    specialty: "英倫風格、經典格紋",
    verified: true,
    niche: false,
  },
  {
    id: "penhaligons",
    name: "Penhaligon's",
    origin: "英國",
    style: "維多利亞時代優雅",
    description: "潘海利根承襲維多利亞時代的優雅傳統，每款香水都充滿故事性。",
    occasions: "正式場合、文化活動、復古主題",
    gender: ["feminine", "masculine"],
    scentTypes: ["warm", "woody"],
    moodTypes: ["classic", "sophisticated"],
    vibeTypes: ["intense", "subtle"],
    specialty: "維多利亞風格、故事性香調",
    verified: true,
    niche: true,
  },
  {
    id: "creed",
    name: "Creed",
    origin: "英國",
    style: "皇室御用香水",
    description: "信仰香水是英國皇室御用品牌，擁有260年的調香歷史。",
    occasions: "特殊場合、正式活動、高端社交",
    gender: ["feminine", "masculine"],
    scentTypes: ["woody", "fresh"],
    moodTypes: ["classic", "sophisticated"],
    vibeTypes: ["intense", "bold"],
    specialty: "皇室傳統、手工調製",
    verified: true,
    niche: false,
  },
  {
    id: "millerharris",
    name: "Miller Harris",
    origin: "英國",
    style: "倫敦現代風格",
    description: "倫敦小眾香水品牌，以現代都市風格和自然靈感聞名。",
    occasions: "都市生活、藝術活動、日常精緻",
    gender: ["feminine", "masculine"],
    scentTypes: ["fresh", "woody"],
    moodTypes: ["modern", "sophisticated"],
    vibeTypes: ["subtle", "soft"],
    specialty: "倫敦風格、自然靈感",
    verified: true,
    niche: true, // 標記為小眾品牌
  },
  {
    id: "beaufortlondon",
    name: "BeauFort London",
    origin: "英國",
    style: "英國海軍歷史",
    description: "以英國海軍歷史為靈感的小眾香水品牌，充滿冒險精神。",
    occasions: "特殊場合、藝術活動、個性表達",
    gender: ["masculine"],
    scentTypes: ["woody", "warm"],
    moodTypes: ["classic", "sophisticated"],
    vibeTypes: ["intense", "bold"],
    specialty: "海軍歷史、冒險精神",
    verified: true,
    niche: true, // 標記為小眾品牌
  },

  // 意大利品牌
  {
    id: "acquadiparma",
    name: "Acqua di Parma",
    origin: "意大利",
    style: "意式優雅生活",
    description: "帕爾瑪之水體現意大利優雅生活方式，清新而精緻。",
    occasions: "日常佩戴、度假旅行、輕鬆社交",
    gender: ["feminine", "masculine"],
    scentTypes: ["fresh"],
    moodTypes: ["classic", "playful"],
    vibeTypes: ["soft", "subtle"],
    specialty: "柑橘香調、意式生活",
    verified: true,
    niche: false,
  },
  {
    id: "dolcegabbana",
    name: "Dolce & Gabbana",
    origin: "意大利",
    style: "地中海熱情",
    description: "杜嘉班納香水充滿地中海的熱情與活力。",
    occasions: "派對聚會、度假旅行、浪漫約會",
    gender: ["feminine", "masculine"],
    scentTypes: ["warm", "fresh"],
    moodTypes: ["playful", "sophisticated"],
    vibeTypes: ["bold", "soft"],
    specialty: "地中海風情、熱情活力",
    verified: true,
    niche: false,
  },
  {
    id: "versace",
    name: "Versace",
    origin: "意大利",
    style: "奢華魅力",
    description: "范思哲香水展現意式奢華與性感魅力。",
    occasions: "晚間活動、特殊場合、派對聚會",
    gender: ["feminine", "masculine"],
    scentTypes: ["warm", "woody"],
    moodTypes: ["sophisticated", "modern"],
    vibeTypes: ["bold", "intense"],
    specialty: "奢華性感、意式魅力",
    verified: true,
    niche: false,
  },
  {
    id: "profumum",
    name: "Profumum Roma",
    origin: "意大利",
    style: "羅馬古典藝術",
    description: "羅馬小眾香水品牌，以高濃度精油和古典藝術靈感聞名。",
    occasions: "特殊場合、藝術活動、收藏鑑賞",
    gender: ["feminine", "masculine"],
    scentTypes: ["warm", "woody"],
    moodTypes: ["classic", "sophisticated"],
    vibeTypes: ["intense", "bold"],
    specialty: "高濃度精油、古典藝術",
    verified: true,
    niche: true, // 標記為小眾品牌
  },
  {
    id: "tiziana",
    name: "Tiziana Terenzi",
    origin: "意大利",
    style: "意大利奢華小眾",
    description: "意大利家族品牌，專注於高濃度香精和獨特配方。",
    occasions: "特殊場合、奢華活動、收藏鑑賞",
    gender: ["feminine", "masculine"],
    scentTypes: ["warm", "woody"],
    moodTypes: ["sophisticated", "classic"],
    vibeTypes: ["intense", "bold"],
    specialty: "高濃度香精、家族工藝",
    verified: true,
    niche: true, // 標記為小眾品牌
  },

  // 美國品牌
  {
    id: "tomford",
    name: "Tom Ford",
    origin: "美國",
    style: "現代奢華主義",
    description: "湯姆福特香水代表現代奢華與性感魅力的完美結合。",
    occasions: "晚間活動、商務場合、特殊約會",
    gender: ["feminine", "masculine"],
    scentTypes: ["woody", "warm"],
    moodTypes: ["sophisticated", "modern"],
    vibeTypes: ["bold", "intense"],
    specialty: "現代奢華、性感魅力",
    verified: true,
    niche: false,
  },
  {
    id: "calvinklein",
    name: "Calvin Klein",
    origin: "美國",
    style: "簡約現代主義",
    description: "卡爾文克萊恩香水體現美式簡約與現代都市生活。",
    occasions: "日常佩戴、運動後、都市生活",
    gender: ["feminine", "masculine"],
    scentTypes: ["fresh"],
    moodTypes: ["modern", "playful"],
    vibeTypes: ["soft", "subtle"],
    specialty: "簡約設計、都市風格",
    verified: true,
    niche: false,
  },
  {
    id: "estee",
    name: "Estée Lauder",
    origin: "美國",
    style: "美式優雅",
    description: "雅詩蘭黛香水代表美式優雅與精緻品味。",
    occasions: "商務場合、正式活動、日常優雅",
    gender: ["feminine"],
    scentTypes: ["warm", "fresh"],
    moodTypes: ["sophisticated", "classic"],
    vibeTypes: ["soft", "subtle"],
    specialty: "美式優雅、精緻品味",
    verified: true,
    niche: false,
  },
  {
    id: "imaginaryauthors",
    name: "Imaginary Authors",
    origin: "美國",
    style: "文學靈感小眾",
    description: "以虛構作家和小說為靈感的美國小眾香水品牌。",
    occasions: "藝術活動、文化場合、個性表達",
    gender: ["feminine", "masculine"],
    scentTypes: ["woody", "fresh"],
    moodTypes: ["modern", "sophisticated"],
    vibeTypes: ["bold", "subtle"],
    specialty: "文學靈感、故事性香調",
    verified: true,
    niche: true, // 標記為小眾品牌
  },
  {
    id: "kerosene",
    name: "Kerosene",
    origin: "美國",
    style: "美國獨立香水",
    description: "密歇根州的獨立香水品牌，以手工製作和獨特風格聞名。",
    occasions: "藝術活動、個性表達、特殊場合",
    gender: ["feminine", "masculine"],
    scentTypes: ["warm", "woody"],
    moodTypes: ["modern", "sophisticated"],
    vibeTypes: ["bold", "intense"],
    specialty: "手工製作、獨立精神",
    verified: true,
    niche: true, // 標記為小眾品牌
  },

  // 瑞典品牌
  {
    id: "byredo",
    name: "Byredo",
    origin: "瑞典",
    style: "北歐極簡主義",
    description: "拜里朵體現北歐極簡美學，每款香水都是現代藝術品。",
    occasions: "藝術場合、現代都市、創意工作",
    gender: ["feminine", "masculine"],
    scentTypes: ["fresh", "woody"],
    moodTypes: ["modern", "sophisticated"],
    vibeTypes: ["subtle", "soft"],
    specialty: "北歐設計、極簡美學",
    verified: true,
    niche: true,
  },
  {
    id: "svenskanumber",
    name: "Svenska Number",
    origin: "瑞典",
    style: "瑞典現代設計",
    description: "瑞典小眾香水品牌，以數字命名和極簡設計聞名。",
    occasions: "現代都市、創意工作、日常精緻",
    gender: ["feminine", "masculine"],
    scentTypes: ["fresh", "woody"],
    moodTypes: ["modern", "sophisticated"],
    vibeTypes: ["subtle", "soft"],
    specialty: "極簡設計、數字概念",
    verified: true,
    niche: true, // 標記為小眾品牌
  },

  // 德國品牌
  {
    id: "jilsander",
    name: "Jil Sander",
    origin: "德國",
    style: "德式極簡主義",
    description: "吉爾桑德香水體現德式極簡與純淨美學。",
    occasions: "商務場合、簡約生活、現代都市",
    gender: ["feminine", "masculine"],
    scentTypes: ["fresh"],
    moodTypes: ["modern", "sophisticated"],
    vibeTypes: ["subtle", "soft"],
    specialty: "極簡純淨、德式設計",
    verified: true,
    niche: false,
  },
  {
    id: "jfschwarze",
    name: "J.F. Schwarzlose",
    origin: "德國",
    style: "柏林歷史香水",
    description: "柏林歷史悠久的香水品牌，融合傳統與現代的小眾香水。",
    occasions: "文化活動、藝術展覽、特殊場合",
    gender: ["feminine", "masculine"],
    scentTypes: ["woody", "fresh"],
    moodTypes: ["classic", "modern"],
    vibeTypes: ["subtle", "bold"],
    specialty: "柏林歷史、現代詮釋",
    verified: true,
    niche: true, // 標記為小眾品牌
  },

  // 西班牙品牌
  {
    id: "loewe",
    name: "Loewe",
    origin: "西班牙",
    style: "西班牙手工藝術",
    description: "羅意威香水承襲西班牙手工藝傳統，每款都充滿藝術氣息。",
    occasions: "文化活動、藝術場合、優雅聚會",
    gender: ["feminine", "masculine"],
    scentTypes: ["warm", "woody"],
    moodTypes: ["sophisticated", "classic"],
    vibeTypes: ["soft", "subtle"],
    specialty: "手工藝術、西班牙風情",
    verified: true,
    niche: false,
  },
  {
    id: "carner",
    name: "Carner Barcelona",
    origin: "西班牙",
    style: "巴塞羅那風情",
    description: "巴塞羅那小眾香水品牌，以地中海風情和城市靈感聞名。",
    occasions: "都市生活、文化活動、度假旅行",
    gender: ["feminine", "masculine"],
    scentTypes: ["warm", "fresh"],
    moodTypes: ["modern", "sophisticated"],
    vibeTypes: ["soft", "subtle"],
    specialty: "地中海風情、城市靈感",
    verified: true,
    niche: true, // 標記為小眾品牌
  },

  // 美國小眾品牌
  {
    id: "lelabo",
    name: "Le Labo",
    origin: "美國",
    style: "手工調製香水",
    description: "勒拉博專注手工調製，每瓶香水都是現場調配的藝術品。",
    occasions: "個性表達、藝術場合、特殊收藏",
    gender: ["feminine", "masculine"],
    scentTypes: ["woody", "fresh"],
    moodTypes: ["modern", "sophisticated"],
    vibeTypes: ["bold", "subtle"],
    specialty: "手工調製、個性化服務",
    verified: true,
    niche: true,
  },

  // 澳洲品牌
  {
    id: "aesop",
    name: "Aesop",
    origin: "澳洲",
    style: "植物學香水",
    description: "伊索香水專注植物學研究，每款都充滿自然純淨的力量。",
    occasions: "日常佩戴、自然環境、簡約生活",
    gender: ["feminine", "masculine"],
    scentTypes: ["fresh", "woody"],
    moodTypes: ["modern", "playful"],
    vibeTypes: ["soft", "subtle"],
    specialty: "植物學研究、自然純淨",
    verified: true,
    niche: true,
  },
  {
    id: "goldfield",
    name: "Goldfield & Banks",
    origin: "澳洲",
    style: "澳洲自然風光",
    description: "以澳洲獨特自然風光和原生植物為靈感的小眾香水品牌。",
    occasions: "戶外活動、自然環境、日常精緻",
    gender: ["feminine", "masculine"],
    scentTypes: ["fresh", "woody"],
    moodTypes: ["modern", "playful"],
    vibeTypes: ["soft", "subtle"],
    specialty: "澳洲風光、原生植物",
    verified: true,
    niche: true, // 標記為小眾品牌
  },

  // 法國小眾品牌
  {
    id: "maison",
    name: "Maison Margiela",
    origin: "法國",
    style: "概念性香水",
    description: "馬丁馬吉拉香水以概念性創作聞名，每款都是嗅覺記憶的重現。",
    occasions: "藝術場合、概念性表達、收藏鑑賞",
    gender: ["feminine", "masculine"],
    scentTypes: ["fresh", "woody"],
    moodTypes: ["modern", "sophisticated"],
    vibeTypes: ["bold", "subtle"],
    specialty: "概念創作、嗅覺記憶",
    verified: true,
    niche: true,
  },
  {
    id: "frederic",
    name: "Frédéric Malle",
    origin: "法國",
    style: "調香師合作平台",
    description: "弗雷德里克馬勒為頂級調香師提供創作平台，每款都是大師作品。",
    occasions: "收藏鑑賞、特殊場合、香水愛好者",
    gender: ["feminine", "masculine"],
    scentTypes: ["woody", "warm"],
    moodTypes: ["sophisticated", "classic"],
    vibeTypes: ["intense", "bold"],
    specialty: "調香師合作、大師作品",
    verified: true,
    niche: true,
  },
  {
    id: "serge",
    name: "Serge Lutens",
    origin: "法國",
    style: "東方神秘主義",
    description: "塞爾日盧騰斯深受東方文化影響，創造充滿詩意的香水藝術。",
    occasions: "藝術展覽、特殊場合、個人收藏",
    gender: ["feminine", "masculine"],
    scentTypes: ["woody", "warm"],
    moodTypes: ["sophisticated", "classic"],
    vibeTypes: ["intense", "bold"],
    specialty: "東方神秘主義、詩意創作",
    verified: true,
    niche: true,
  },
  {
    id: "nicolai",
    name: "Parfums de Nicolaï",
    origin: "法國",
    style: "法式調香世家",
    description: "由調香世家後裔Patricia de Nicolaï創立的獨立香水品牌。",
    occasions: "日常精緻、文化活動、特殊場合",
    gender: ["feminine", "masculine"],
    scentTypes: ["fresh", "warm"],
    moodTypes: ["classic", "sophisticated"],
    vibeTypes: ["subtle", "soft"],
    specialty: "調香世家、獨立精神",
    verified: true,
    niche: true, // 標記為小眾品牌
  },
  {
    id: "parfumdempire",
    name: "Parfum d'Empire",
    origin: "法國",
    style: "帝國風格香水",
    description: "以古代帝國為靈感的法國小眾香水品牌，充滿歷史感。",
    occasions: "特殊場合、文化活動、收藏鑑賞",
    gender: ["feminine", "masculine"],
    scentTypes: ["warm", "woody"],
    moodTypes: ["sophisticated", "classic"],
    vibeTypes: ["bold", "intense"],
    specialty: "帝國靈感、歷史感",
    verified: true,
    niche: true, // 標記為小眾品牌
  },

  // 阿曼品牌
  {
    id: "amouage",
    name: "Amouage",
    origin: "阿曼",
    style: "阿拉伯奢華",
    description: "阿蒙阿吉是阿曼皇室香水品牌，代表阿拉伯奢華香水的極致。",
    occasions: "特殊場合、奢華活動、收藏鑑賞",
    gender: ["feminine", "masculine"],
    scentTypes: ["woody", "warm"],
    moodTypes: ["sophisticated", "classic"],
    vibeTypes: ["intense", "bold"],
    specialty: "阿拉伯奢華、皇室品質",
    verified: true,
    niche: true,
  },

  // 法國奢華品牌
  {
    id: "montale",
    name: "Montale",
    origin: "法國",
    style: "東方奢華香調",
    description: "蒙塔萊專注東方奢華香調，以玫瑰和沉香聞名。",
    occasions: "特殊場合、晚間活動、奢華聚會",
    gender: ["feminine", "masculine"],
    scentTypes: ["woody", "warm"],
    moodTypes: ["sophisticated", "classic"],
    vibeTypes: ["intense", "bold"],
    specialty: "東方奢華、玫瑰沉香",
    verified: true,
    niche: true,
  },

  // 英國小眾品牌
  {
    id: "ormonde",
    name: "Ormonde Jayne",
    origin: "英國",
    style: "英式奢華小眾",
    description: "奧蒙德傑恩是英國奢華小眾品牌，以精緻調香聞名。",
    occasions: "優雅聚會、文化活動、精緻生活",
    gender: ["feminine", "masculine"],
    scentTypes: ["fresh", "woody"],
    moodTypes: ["sophisticated", "classic"],
    vibeTypes: ["subtle", "soft"],
    specialty: "英式奢華、精緻調香",
    verified: true,
    niche: true,
  },

  // 法國古龍水品牌
  {
    id: "atelier",
    name: "Atelier Cologne",
    origin: "法國",
    style: "現代古龍水",
    description: "歐瓏重新定義古龍水，創造現代精緻的柑橘香調。",
    occasions: "日常佩戴、清新時光、都市生活",
    gender: ["feminine", "masculine"],
    scentTypes: ["fresh"],
    moodTypes: ["modern", "playful"],
    vibeTypes: ["soft", "subtle"],
    specialty: "現代古龍水、柑橘專家",
    verified: true,
    niche: true,
  },

  // 法國詩意品牌
  {
    id: "annick",
    name: "Annick Goutal",
    origin: "法國",
    style: "法式詩意浪漫",
    description: "安妮古特香水充滿法式詩意與浪漫情懷。",
    occasions: "浪漫約會、詩意時光、文藝活動",
    gender: ["feminine"],
    scentTypes: ["fresh", "warm"],
    moodTypes: ["playful", "sophisticated"],
    vibeTypes: ["soft", "subtle"],
    specialty: "詩意浪漫、法式情懷",
    verified: true,
    niche: true,
  },

  // 法國手工藝品牌
  {
    id: "artisan",
    name: "L'Artisan Parfumeur",
    origin: "法國",
    style: "法式手工藝香水",
    description: "工匠香水師是法國手工藝香水的先驅，每款都是藝術創作。",
    occasions: "藝術場合、手工藝展示、文化活動",
    gender: ["feminine", "masculine"],
    scentTypes: ["fresh", "woody"],
    moodTypes: ["sophisticated", "classic"],
    vibeTypes: ["subtle", "soft"],
    specialty: "手工藝術、法式創作",
    verified: true,
    niche: true,
  },

  // 英國傳統品牌
  {
    id: "floris",
    name: "Floris London",
    origin: "英國",
    style: "英倫傳統香水",
    description: "弗洛里斯是英國最古老的香水品牌，承載三世紀的傳統。",
    occasions: "傳統儀式、英式下午茶、經典場合",
    gender: ["feminine", "masculine"],
    scentTypes: ["fresh", "woody"],
    moodTypes: ["classic", "sophisticated"],
    vibeTypes: ["subtle", "soft"],
    specialty: "英倫傳統、三世紀傳承",
    verified: true,
    niche: true,
  },

  // 中東品牌
  {
    id: "xerjoff",
    name: "Xerjoff",
    origin: "義大利/中東",
    style: "奢華藝術香水",
    description: "融合義大利工藝與中東香料的奢華小眾品牌。",
    occasions: "特殊場合、奢華活動、收藏鑑賞",
    gender: ["feminine", "masculine"],
    scentTypes: ["warm", "woody"],
    moodTypes: ["sophisticated", "classic"],
    vibeTypes: ["intense", "bold"],
    specialty: "奢華工藝、珍貴原料",
    verified: true,
    niche: true, // 標記為小眾品牌
  },
  {
    id: "nasomatto",
    name: "Nasomatto",
    origin: "義大利",
    style: "實驗性香水藝術",
    description: "由義大利調香師Alessandro Gualtieri創立的實驗性香水品牌。",
    occasions: "藝術場合、個性表達、特殊收藏",
    gender: ["feminine", "masculine"],
    scentTypes: ["woody", "warm"],
    moodTypes: ["modern", "sophisticated"],
    vibeTypes: ["bold", "intense"],
    specialty: "實驗性創作、藝術表達",
    verified: true,
    niche: true, // 標記為小眾品牌
  },
  {
    id: "memo",
    name: "Memo Paris",
    origin: "法國",
    style: "旅行靈感香水",
    description: "以世界各地旅行記憶為靈感的小眾香水品牌。",
    occasions: "旅行、文化活動、特殊場合",
    gender: ["feminine", "masculine"],
    scentTypes: ["fresh", "woody"],
    moodTypes: ["sophisticated", "modern"],
    vibeTypes: ["bold", "subtle"],
    specialty: "旅行靈感、文化融合",
    verified: true,
    niche: true, // 標記為小眾品牌
  },
  {
    id: "zoologist",
    name: "Zoologist",
    origin: "加拿大",
    style: "動物靈感香水",
    description: "以動物世界為靈感的創新小眾香水品牌。",
    occasions: "藝術場合、特殊收藏、個性表達",
    gender: ["feminine", "masculine"],
    scentTypes: ["woody", "fresh"],
    moodTypes: ["modern", "sophisticated"],
    vibeTypes: ["bold", "intense"],
    specialty: "動物靈感、創新概念",
    verified: true,
    niche: true, // 標記為小眾品牌
  },
  {
    id: "vilhelm",
    name: "Vilhelm Parfumerie",
    origin: "瑞典/法國",
    style: "北歐故事香水",
    description: "由瑞典設計師創立，融合北歐故事與法式調香的小眾品牌。",
    occasions: "文化活動、藝術場合、日常精緻",
    gender: ["feminine", "masculine"],
    scentTypes: ["fresh", "warm"],
    moodTypes: ["modern", "sophisticated"],
    vibeTypes: ["subtle", "bold"],
    specialty: "北歐故事、法式調香",
    verified: true,
    niche: true, // 標記為小眾品牌
  },
]

// 獲取已驗證的品牌
export function getVerifiedBrands() {
  return COMPREHENSIVE_BRAND_DATABASE.filter((brand) => brand.verified === true)
}

// 根據性別獲取品牌
export function getBrandsByGender(gender: string) {
  return getVerifiedBrands().filter((brand) => brand.gender.includes(gender))
}

// 獲取小眾品牌
export function getNicheBrands(gender: string) {
  return getVerifiedBrands().filter((brand) => brand.gender.includes(gender) && brand.niche === true)
}

// 獲取知名品牌（用於緊急備用）
export function getPremiumBrands(gender: string) {
  const premiumBrandIds =
    gender === "feminine"
      ? ["chanel", "dior", "hermes", "guerlain", "lancome"]
      : ["tomford", "creed", "hermes", "guerlain", "cdg"]

  return premiumBrandIds.map((id) => COMPREHENSIVE_BRAND_DATABASE.find((brand) => brand.id === id)).filter(Boolean)
}
