-- Add test subscription data for the current user
INSERT INTO subscribers (
  user_id,
  name,
  email,
  phone,
  address,
  city,
  postal_code,
  country,
  subscription_status,
  payment_status,
  payment_method,
  monthly_fee,
  created_at,
  updated_at,
  last_payment_date,
  next_payment_date,
  quiz_answers,
  payment_data
) VALUES (
  '15016f67-e8e4-42a4-b163-8d0c98c9ce4f',
  '涂旭含',
  'tusummer1214@gmail.com',
  '0912345678',
  '台北市信義區信義路五段7號',
  '台北市',
  '110',
  '台灣',
  'active',
  'paid',
  'credit_card',
  1200,
  NOW(),
  NOW(),
  NOW() - INTERVAL '1 month',
  NOW() + INTERVAL '1 month',
  '{"fragrance_preference": "fresh", "intensity": "medium", "occasion": "daily"}',
  '{"merchant_order_no": "TEST001", "period_no": "1"}'
);

-- Add a few more test records to show subscription history
INSERT INTO subscribers (
  user_id,
  name,
  email,
  phone,
  address,
  city,
  postal_code,
  country,
  subscription_status,
  payment_status,
  payment_method,
  monthly_fee,
  created_at,
  updated_at,
  last_payment_date,
  next_payment_date,
  quiz_answers,
  payment_data
) VALUES (
  '15016f67-e8e4-42a4-b163-8d0c98c9ce4f',
  '涂旭含',
  'tusummer1214@gmail.com',
  '0912345678',
  '台北市信義區信義路五段7號',
  '台北市',
  '110',
  '台灣',
  'completed',
  'paid',
  'credit_card',
  1200,
  NOW() - INTERVAL '2 months',
  NOW() - INTERVAL '1 month',
  NOW() - INTERVAL '2 months',
  NOW() - INTERVAL '1 month',
  '{"fragrance_preference": "fresh", "intensity": "medium", "occasion": "daily"}',
  '{"merchant_order_no": "TEST002", "period_no": "2"}'
);
